### ISSUE TITLE
Will the dataset used in this paper be made public?

### ISSUE THREAD

**Issue by GoldenUpwinds** [PRBonn/HortiMapping#1]
I have noticed that this paper has created a dataset that includes both fruits and robots. Will this dataset be made public, including the visual-inertial information and the robot's ground truth data?

**Comment by YuePanEdward** [comment]
Sorry for the very late reply.
We have recently provided a public dataset and benchmark on fruit shape completion in the greenhouse. The RGB-D images, instance labels of the fruits and the camera poses of the robot are provided. The ground truth shape point clouds measured by the handheld scanner are also provided for the training split. 
For more details, please check the report: https://arxiv.org/pdf/2407.13304 
and the dataset webpage: https://www.ipb.uni-bonn.de/data/shape_completion/index.html
